[build-system]
build-backend = "setuptools.build_meta"

requires = ["setuptools>=67.8", "setuptools-scm>=8"]

[project]
name = "da4ml-torch"
description = "da4ml converter provider for torch"
readme = "README.md"
keywords = ["da4ml", "torch"]
license = 'LGPL-3.0-only'
authors = [{ name = "Chang Sun", email = "chsun@cern.ch" }]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dynamic = ["version"]

dependencies = ["da4ml", "torch", "torchlogix"]
urls.repository = "https://github.com/calad0i/da4ml-torch"

entry-points."dais_tracer.plugins".torch = "da4ml_torch.parser:TorchParser"
entry-points."dais_tracer.plugins".torchlogix = "da4ml_torch.parser:TorchParser"

[project.scripts]
da4ml-torch-convert = "da4ml_torch.tools.torchlogix_to_da4ml:main"
da4ml-torch-estimate = "da4ml_torch.tools.torchlogix_to_da4ml:estimate_main"
da4ml-torchlogix-convert = "da4ml_torch.tools.torchlogix_to_da4ml:main"

[tool.setuptools]
include-package-data = true
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["da4ml_torch*"]

[tool.setuptools_scm]
write_to = "src/da4ml_torch/_version.py"

[tool.ruff]
target-version = "py310"

line-length = 130
indent-width = 4

include = ["src/da4ml_torch/**/*.py"]

format.indent-style = "space"
format.quote-style = "single"
format.skip-magic-trailing-comma = false
format.docstring-code-line-length = 130
format.docstring-code-format = true
lint.select = ["E", "F", "F401", "I", "W"]
lint.ignore = ["E501", "F403", "F405"]
lint.explicit-preview-rules = true
lint.fixable = ["ALL"]
lint.unfixable = []
